### ISSUE TITLE
Asignar nombre red y versión para Traeffik

### ISSUE THREAD

**Issue by ssheduardo** [atareao/self-hosted#13]
Hola muy buenas, estuve probando Traeffik con tu receta y ha funcionado genial, quería aportar alguna sugerencia de poder asignar el nombre de red y versión.
Modificando el archivo docker-compose.yml quedaría algo así:

```
version: '3'

services:
  traefik:
    image: traefik:${VERSION}
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./users.txt:/users.txt:ro
      - ./acme.json:/acme.json
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.basicauth.basicauth.usersfile=/users.txt
      - traefik.http.routers.traefik-secure.entrypoints=websecure
      - traefik.http.routers.traefik-secure.rule=Host(`${HOSTNAME}`)
      - traefik.http.routers.traefik-secure.middlewares=basicauth
      - traefik.http.routers.traefik-secure.tls=true
      - traefik.http.routers.traefik-secure.tls.certresolver=letsencrypt
      - traefik.http.routers.traefik-secure.service=api@internal


#Docker Networks
networks:
    default:
        external:
            name: ${NETWORK}        

```

Y el punto .env
```
HOSTNAME="traefik.tuserver.com"
NETWORK="traefik_net"
VERSION="v2.9"

```

Si en una futura actualización puedes agregarlo genial, más que todo para no modificar el archivo docker-compose.yml.
