### ISSUE TITLE
Error en traefik.yml

### ISSUE THREAD

**Issue by Vctrsnts** [atareao/self-hosted#33]
Buenas.

En el fichero de configuración de `traefik.yml`, tienes puesto lo siguiente:
```
certificatesResolvers:
  letsencrypt:
    acme:
      email: tu@correo.es
      storage: acme.json
      httpChallenge:
        entryPoint: web
  cloudflare:
    acme:
      email: tu@correo.es
      storage: acme.json
      keyType: EC256
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "1.0.0.1:53"
```
Que entiendo que es para la validación de los certificados pero creo que no funciona, porque lo he probado y me dice que no puedes poner el mismo mail en los dos sitios, porque como "_se validan_", en concreto este error:

`ERR Command error error="command traefik error: unable to initialize certificates resolver \"letsencrypt\", as all ACME resolvers must use the same email"`

Que tiene que ser mails diferentes?

Asi mismo, cuando estas con el _traefik-real-ip_ en el fichero `dynamic.yml` y lo vas a usar en algun contenedor, en la web de traefik, indica que el plugin traefik-real-ip es desconocido. Es correcto la definición de ese plugin??

Gracias
