### ISSUE TITLE
Filebrowser

### ISSUE THREAD

**Issue by damufo** [atareao/self-hosted#6]
Gracias por tu atención Lorenzo.

No soy capaz de hacer funcionar filebrowser con traefik y letsencrypt

Con el puerto 80 falla, no arranca
2022/09/06 06:01:20 listen tcp :80: bind: permission denied

Si cambio el puerto en filebrowser.json
Failed to connect to localhost port 80 after 4 ms: Connection refused
arranca pero no va con traefik

Aquí parece que llegan a la conclusión de que no va
https://github.com/filebrowser/filebrowser/issues/152

Gracias

**Comment by atareao** [comment]
Hola,
Yo lo tengo levantado desde hace mucho tiempo y por el puerto 80.
¿Estás utilizando el docker-compose que hay en el repositorio?
Puedes compartir tu docker-compose?

**Comment by damufo** [comment]
Gracias Lorenzo!

Te envié un mensaje por correo con captura de los contenedores levantados en el equipo.

docker-compose.yml
 
version: '3'

services:
  filebrowser2:
    image: filebrowser/filebrowser
    container_name: filebrowser2
    restart: unless-stopped
    user: ${UID}:${GID}
    volumes:
      - /home/damufo/data/www/tprd:/srv
      - ./filebrowser.db:/database.db
      - ./filebrowser.json:/.filebrowser.json


filebrowser.json
{
  "port": 80,
  "baseURL": "",
  "address": "",
  "log": "stdout",
  "database": "/database.db",
  "root": "/srv"
}

**Comment by atareao** [comment]
Pero ¿has utilizado algún Proxy Inverso?

**Comment by damufo** [comment]
Muchas gracias por la respuesta Lorenzo 🙂

Sí, tengo traefik funcionando perfectamente para otros contenedores, el primer filebrowser es el mio, funciona pero no se por qué no crea el certificado lets encript.
Esto es del mío:
![imaxe](https://user-images.githubusercontent.com/4057369/191658767-85c66dba-fcf0-4dcd-84e9-113d19e3f255.png)

El segundo filebrowser2 es el tuyo (es el self-hostied), no arranca: 
![imaxe](https://user-images.githubusercontent.com/4057369/191658901-e386f8b2-552b-47fe-b439-1aabd822b0b2.png)

Estos son otros contenedores en la misma máquina funcionando con traefik en los que traefik parece funcionar perfectamente con su certificado creado sin problema:
![imaxe](https://user-images.githubusercontent.com/4057369/191658492-051c30af-3d33-42ba-b75b-b67b34124d0e.png)

Y este es el código del docker-compose del traefik (hay más servicios en este docker-compose):
```
  traefik:
    container_name: traefik
    image: traefik:v2.0
    command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--entryPoints.web.address=:80"
        - "--entryPoints.websecure.address=:443"
        - "--certificatesResolvers.le.acme.email=usuario_traef@correousuario_traef.org"
        - "--certificatesResolvers.le.acme.storage=acme.json"
        - "--certificatesResolvers.le.acme.tlsChallenge=true"
        - "--certificatesResolvers.le.acme.httpChallenge=true"
        - "--certificatesResolvers.le.acme.httpChallenge.entryPoint=web"
    restart: unless-stopped
    ports:
        - 80:80
        - 443:443
        - 8080:8080
    networks:
        - web
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
        - "./traefik/acme.json:/acme.json"
    labels:
        # Redirect all HTTP to HTTPS permanently
        - traefik.http.routers.http_catchall.rule=HostRegexp(`{any:.+}`)
        - traefik.http.routers.http_catchall.entrypoints=web
        - traefik.http.routers.http_catchall.middlewares=https_redirect
        - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
```
Para todos los servicios traefik, funciona bien excepto para los filebrowser
Muchas gracias Lorenzo nuevamente.

**Comment by atareao** [comment]
Lo que no veo en el docker-compose.yml de filebrowser son los labels... ¿no los has puesto?

**Comment by damufo** [comment]
Los comenté porque no arranca, también probé a publicar el puerto para acceder localmente. El problema es que no arranca.
Son los tuyos, cambiando el nombre del contenedor y la red que la mía se llama web.
```
services:
  filebrowser2:
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.services.filebrowser2.loadbalancer.server.port=80
      - traefik.http.routers.filebrowser2.entrypoints=web
      - traefik.http.routers.filebrowser2.rule=Host(`${FQDN}`)
      - traefik.http.middlewares.filebrowser2-https-redirect.redirectscheme.scheme=websecure
      - traefik.http.routers.filebrowser2.middlewares=filebrowser2-https-redirect
      - traefik.http.routers.filebrowser2-secure.entrypoints=websecure
      - traefik.http.routers.filebrowser2-secure.rule=Host(`${FQDN}`)
      - traefik.http.routers.filebrowser2-secure.tls=true
      - traefik.http.routers.filebrowser2-secure.tls.certresolver=le

networks:
  web:
    external: true
```

**Comment by atareao** [comment]
Y el FQDN es distinto en los dos claro

**Comment by damufo** [comment]
Así es, filebrowser2 tiene distinto.
El problema es que no arranque, yo creo que no es problema de traefik.

**Comment by atareao** [comment]
Me resulta muy raro que uno te funcione y otro no.
A ver si pruebo

**Comment by damufo** [comment]
Hola Lorenzo:

El que funciona (con el fallo del https:) es distinto, este arranca, te paso el docker-compose para que veas la diferencia:

```
version: '3'


networks:                                                                       
  web:                                                                          
    external: true 


services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    ports:
      - 9071:8234
    volumes:
      - "${FILE_BROWSER_DATA_FOLDER}:/srv"
      - "./filebrowser/filebrowser.db:/database.db"
      - "./filebrowser/filebrowser.json:/.filebrowser.json"
    user: "${UID}:${GID}" 
    restart: unless-stopped

    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.docker.network=web
      - traefik.http.routers.filebrowser.rule=Host(`filebrowser.${DOMAIN_SERVER_BASE}`)
      - traefik.http.routers.filebrowser.entrypoints=web,websecure,traefik
      - traefik.http.routers.filebrowser.tls=true
      - traefik.http.routers.filebrowser.service=filebrowser
      - traefik.http.services.filebrowser.loadbalancer.server.port=8234
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8234/health"]
      interval: 30s
      timeout: 20s
      retries: 3

```
